apiVersion: v1
data:
  ADMIN_PASSWORD: IAMSECRET
  DB_DATABASE: describo
  DB_HOST: postgresql
  DB_PASSWORD: admin
  DB_PORT: '5432'
  DB_USER: admin
  LOG_LEVEL: info
  NODE_ENV: production
kind: ConfigMap
metadata:
  labels: {}
  name: describoconfig
