apiVersion: v1
data:
  ping_liveness_local.sh: "#!/bin/sh\nset -e\nif [ ! -z \"$REDIS_PASSWORD\" ]; then\
    \ export REDISCLI_AUTH=$REDIS_PASSWORD; fi;\nresponse=$(\n  timeout -s 3 $1 \\\
    \n  redis-cli \\\n    -h localhost \\\n    -p $REDIS_PORT \\\n    ping\n)\nif\
    \ [ \"$?\" -eq \"124\" ]; then\n  echo \"Timed out\"\n  exit 1\nfi\nresponseFirstWord=$(echo\
    \ $response | head -n1 | awk '{print $1;}')\nif [ \"$response\" != \"PONG\" ]\
    \ && [ \"$responseFirstWord\" != \"LOADING\" ] && [ \"$responseFirstWord\" !=\
    \ \"MASTERDOWN\" ]; then\n  echo \"$response\"\n  exit 1\nfi"
  ping_readiness_local.sh: "#!/bin/sh\nset -e\n\nREDIS_STATUS_FILE=/tmp/.redis_cluster_check\n\
    if [ ! -z \"$REDIS_PASSWORD\" ]; then export REDISCLI_AUTH=$REDIS_PASSWORD; fi;\n\
    response=$(\n  timeout -s 3 $1 \\\n  redis-cli \\\n    -h localhost \\\n    -p\
    \ $REDIS_PORT \\\n    ping\n)\nif [ \"$?\" -eq \"124\" ]; then\n  echo \"Timed\
    \ out\"\n  exit 1\nfi\nif [ \"$response\" != \"PONG\" ]; then\n  echo \"$response\"\
    \n  exit 1\nfi\nif [ ! -f \"$REDIS_STATUS_FILE\" ]; then\n  response=$(\n    timeout\
    \ -s 3 $1 \\\n    redis-cli \\\n      -h localhost \\\n      -p $REDIS_PORT \\\
    \n      CLUSTER INFO | grep cluster_state | tr -d '[:space:]'\n  )\n  if [ \"\
    $?\" -eq \"124\" ]; then\n    echo \"Timed out\"\n    exit 1\n  fi\n  if [ \"\
    $response\" != \"cluster_state:ok\" ]; then\n    echo \"$response\"\n    exit\
    \ 1\n  else\n    touch \"$REDIS_STATUS_FILE\"\n  fi\nfi"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: customerrds
    app.kubernetes.io/name: redis
  name: redis-scripts
