apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: research-data-services.org
    app.kubernetes.io/instance: customerrds
    app.kubernetes.io/name: layer0-describo
    app.kubernetes.io/part-of: service
    app.kubernetes.io/version: '1.0'
    research-data-services.org/layer: layer0
  name: layer0-describo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: research-data-services.org
      app.kubernetes.io/instance: customerrds
      app.kubernetes.io/name: layer0-describo
      app.kubernetes.io/part-of: service
      app.kubernetes.io/version: '1.0'
      research-data-services.org/layer: layer0
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: '2022-11-08T18:14:46Z'
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: research-data-services.org
        app.kubernetes.io/instance: customerrds
        app.kubernetes.io/name: layer0-describo
        app.kubernetes.io/part-of: service
        app.kubernetes.io/version: '1.0'
        research-data-services.org/layer: layer0
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: mservice
            - configMapRef:
                name: proxy
            - configMapRef:
                name: globalenvvar
            - configMapRef:
                name: describoconfig
          image: docker.io/arkisto/describo-online-api:0.26.6
          imagePullPolicy: Always
          name: api
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /srv/api/configuration.json
              name: describo-configuration
              readOnly: true
              subPath: configuration.json
            - mountPath: /srv/profiles/type-definitions-lookup.json
              name: describo-configuration
              readOnly: true
              subPath: type-definitions-lookup.json
            - mountPath: /srv/profiles/type-definitions.json
              name: describo-configuration
              readOnly: true
              subPath: type-definitions.json
        - env:
            - name: VUE_APP_BASE_URL
              value: /
            - name: NODE_ENV
              value: production
          envFrom:
            - configMapRef:
                name: mservice
            - configMapRef:
                name: proxy
            - configMapRef:
                name: globalenvvar
          image: docker.io/arkisto/describo-online-ui:0.26.6
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: ui
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf
              name: describo-configuration
              readOnly: true
              subPath: nginx.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            items:
              - key: configuration.json
                path: configuration.json
              - key: type-definitions-lookup.json
                path: type-definitions-lookup.json
              - key: type-definitions.json
                path: type-definitions.json
              - key: nginx.conf
                path: nginx.conf
            name: describo-configuration-file
          name: describo-configuration
