apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: research-data-services.org
    app.kubernetes.io/instance: customerrds
    app.kubernetes.io/name: layer1-port-owncloud
    app.kubernetes.io/part-of: connector
    app.kubernetes.io/version: '1.0'
    research-data-services.org/layer: layer1
  name: layer1-port-owncloud
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: research-data-services.org
      app.kubernetes.io/instance: customerrds
      app.kubernetes.io/name: layer1-port-owncloud
      app.kubernetes.io/part-of: connector
      app.kubernetes.io/version: '1.0'
      research-data-services.org/layer: layer1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: research-data-services.org
        app.kubernetes.io/instance: customerrds
        app.kubernetes.io/name: layer1-port-owncloud
        app.kubernetes.io/part-of: connector
        app.kubernetes.io/version: '1.0'
        research-data-services.org/layer: layer1
    spec:
      containers:
        - env:
            - name:   OWNCLOUD_INSTALLATION_URL
              value: https://sunet.drive.test.sunet.se
            - name:   OWNCLOUD_OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: owncloud_oauth_client_id
                  key: "client_id"
            - name:   OWNCLOUD_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: owncloud_oauth_client_secret
                  key: "client_secret"
            - name:   SERVICENAME
              value: sunet-drive-test-sunet-se
          envFrom:
            - configMapRef:
                name: mservice
            - configMapRef:
                name: proxy
            - configMapRef:
                name: globalenvvar
          image: zivgitlab.wwu.io/sciebo-rds/sciebo-rds/port_owncloud:v0.1.9
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /metrics
              port: http
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: layer1-port-owncloud
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /metrics
              port: http
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
