apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 
resources:
  - cm-describo-configuration-file.yaml
  - cm-describoconfig.yaml
  - cm-describohelperconfig.yaml
  - cm-domainsconfig.yaml
  - cm-globalenvvar.yaml
  - cm-layer3researchconfig.yaml
  - cm-layer3tokenconfig.yaml
  - cm-mservice.yaml
  - cm-proxy.yaml
  - cm-redis-default.yaml
  - cm-redis-helper-configuration.yaml
  - cm-redis-helper-health.yaml
  - cm-redis-helper-scripts.yaml
  - cm-redis-scripts.yaml
  - cm-serviceexporterconfig.yaml
  - cm-servicemetadataconfig.yaml
  - cm-serviceportconfig.yaml
  - cm-webconfig.yaml
  - deploy-layer0-describo.yaml
  - deploy-layer0-helper-describo-token-updater.yaml
  - deploy-layer0-web.yaml
  - deploy-layer1-port-doris.yaml
  - deploy-layer1-port-owncloud.yaml
  - deploy-layer2-exporter-service.yaml
  - deploy-layer2-metadata-service.yaml
  - deploy-layer2-port-service.yaml
  - deploy-layer3-research-manager.yaml
  - deploy-layer3-token-storage.yaml
  - deploy-postgresql.yaml
  - ing-describo-ingress.yaml
  - ing-layer0-describo.yaml
  - ing-layer0-web.yaml
  - ing-rds-ingress.yaml
  - kustomization.yaml
  - ns-rds.yaml
  - sa-default.yaml
  - sa-redis-helper.yaml
  - sts-redis-helper-master.yaml
  - sts-redis.yaml
  - svc-drive.yaml
  - svc-layer0-describo.yaml
  - svc-layer0-web.yaml
  - svc-layer1-port-doris.yaml
  - svc-layer1-port-owncloud.yaml
  - svc-layer2-exporter-service.yaml
  - svc-layer2-metadata-service.yaml
  - svc-layer2-port-service.yaml
  - svc-layer3-research-manager.yaml
  - svc-layer3-token-storage.yaml
  - svc-postgresql.yaml
  - svc-redis-headless.yaml
  - svc-redis-helper-headless.yaml
  - svc-redis-helper-master.yaml
  - svc-redis.yaml
