apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: research-data-services.org
    app.kubernetes.io/instance: customerrds
    app.kubernetes.io/name: layer3-token-storage
    app.kubernetes.io/part-of: core
    app.kubernetes.io/version: '1.0'
    research-data-services.org/layer: layer3
  name: layer3-token-storage
spec:
  clusterIP: 10.152.183.170
  clusterIPs:
    - 10.152.183.170
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: customerrds
    app.kubernetes.io/name: layer3-token-storage
  sessionAffinity: None
  type: ClusterIP
