apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: customerrds
    app.kubernetes.io/name: redis
  name: redis-headless
spec:
  clusterIP: None
  clusterIPs:
    - None
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: tcp-redis
      port: 6379
      protocol: TCP
      targetPort: tcp-redis
    - name: tcp-redis-bus
      port: 16379
      protocol: TCP
      targetPort: tcp-redis-bus
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: customerrds
    app.kubernetes.io/name: redis
  sessionAffinity: None
  type: ClusterIP
