apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql
    app.kubernetes.io/instance: customerrds
  name: postgresql
spec:
  clusterIP: 10.152.183.54
  clusterIPs:
    - 10.152.183.54
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres
  sessionAffinity: None
  type: ClusterIP
