apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: customerrds
    app.kubernetes.io/name: redis
  name: redis
spec:
  clusterIP: 10.152.183.200
  clusterIPs:
    - 10.152.183.200
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: tcp-redis
      port: 6379
      protocol: TCP
      targetPort: tcp-redis
  selector:
    app.kubernetes.io/instance: customerrds
    app.kubernetes.io/name: redis
  sessionAffinity: None
  type: ClusterIP
