apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: customerrds
    app.kubernetes.io/name: redis-helper
  name: redis-helper-headless
spec:
  clusterIP: None
  clusterIPs:
    - None
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: tcp-redis
      port: 6379
      protocol: TCP
      targetPort: redis
  selector:
    app.kubernetes.io/instance: customerrds
    app.kubernetes.io/name: redis-helper
  sessionAffinity: None
  type: ClusterIP
