apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: research-data-services.org
    app.kubernetes.io/instance: customerrds
    app.kubernetes.io/name: layer1-port-owncloud
    app.kubernetes.io/part-of: connector
    app.kubernetes.io/version: '1.0'
    research-data-services.org/layer: layer1
  name: layer1-port-owncloud
spec:
  clusterIP: 10.152.183.178
  clusterIPs:
    - 10.152.183.178
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: customerrds
    app.kubernetes.io/name: layer1-port-owncloud
  sessionAffinity: None
  type: ClusterIP
