apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: research-data-services.org
    app.kubernetes.io/instance: customerrds
    app.kubernetes.io/name: layer2-metadata-service
    app.kubernetes.io/part-of: service
    app.kubernetes.io/version: '1.0'
    research-data-services.org/layer: layer2
  name: layer2-metadata-service
spec:
  clusterIP: 10.152.183.224
  clusterIPs:
    - 10.152.183.224
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: customerrds
    app.kubernetes.io/name: layer2-metadata-service
  sessionAffinity: None
  type: ClusterIP
