---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: freitag-node
  namespace: freitag
  labels:
    app: freitag-node
spec:
  replicas: 2
  serviceName: nextcloudcluster
  selector:
    matchLabels:
      app: freitag-node
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: server-storage
      namespace: freitag
    spec:
      storageClassName: openebs-jiva-3repl
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Mi
  template:
    metadata:
      labels:
        app: freitag-node
    spec:
      volumes:
        - name: nextcloud-config-template
          configMap:
            name: nextcloud-configmap
            items:
              - key: "config.php"
                path: "config.php"
      containers:
      - name: nextcloud 
        image: nextcloud 
        volumeMounts:
        - name: server-storage
          mountPath: /var/www/html/config
          subPath: server-data
        resources: {}
      initContainers:
      - image: docker.sunet.se/sunet/docker-jinja:latest
        name: init-config
        volumeMounts:
        - name: nextcloud-config-template
          mountPath: /tmp/config.php.template
          subPath: config.php
        - name: server-storage
          mountPath: /var/www/html/config
          subPath: server-data
        env:
          - name: MYSQL_DATABASE
            value: "freitag_nextcloud"
          - name: MYSQL_USER
            value: "freitag"
          - name: MYSQL_HOST
            value: "proxysql.proxysql"
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: "db_password"
          - name: MYSQL_PORT
            value: "6033"
          - name: NEXTCLOUD_TRUSTED_DOMAINS
            value: "freitag.drive.test.sunet.se"
          - name: NEXTCLOUD_ADMIN_USER
            value: _freitag
          - name: NEXTCLOUD_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nc-secret
                key: "nc_admin_password"
          - name: OBJECTSTORE_S3_REGION
            value: "us-east-1"
          - name: OBJECTSTORE_S3_HOST
            value: "s3.sto4.safedc.net"
          - name: OBJECTSTORE_S3_BUCKET
            value: "primary-freitag-drive-test.sunet.se"
          - name: OBJECTSTORE_S3_KEY
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: "s3_key"
          - name: OBJECTSTORE_S3_SECRET
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: "s3_secret"
          - name: OBJECTSTORE_S3_USEPATH_STYLE
            value: "true"
          - name: OBJECTSTORE_S3_AUTOCREATE
            value: "true"
          - name: OBJECTSTORE_S3_SSL
            value: "true"
          - name: REDIS_HOST
            value: "redis.redis"
          - name: REDIS_DBINDEX
            value: 42
        command: ["/bin/sh", "-c", "/usr/bin/test -f /var/www/html/config/config.php || /usr/bin/j2 -f env -o /var/www/html/config/config.php /tmp/config.php.template"]
