apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-configmap
  namespace: freitag
data: 
  config.php: |
    <?php
    \$CONFIG = array (
      'htaccess.RewriteBase' => '/',
      'memcache.local' => '\\OC\\Memcache\\APCu',
      'apps_paths' => 
      array (
        0 => 
        array (
          'path' => '/var/www/html/apps',
          'url' => '/apps',
          'writable' => false,
        ),
        1 => 
        array (
          'path' => '/var/www/html/custom_apps',
          'url' => '/custom_apps',
          'writable' => true,
        ),
      ),
      'memcache.distributed' => '\\OC\\Memcache\\Redis',
      'memcache.locking' => '\\OC\\Memcache\\Redis',
      'redis' => 
      array (
        'host' => '{{REDIS_HOST}}',
        'password' => '{{REDIS_HOST_PASSWORD}}',
        'port' => 6379,
        'dbindex'  => {{REDIS_DBINDEX}},
      ),
      'objectstore' => 
      array (
        'class' => '\\OC\\Files\\ObjectStore\\S3',
        'arguments' => 
        array (
          'bucket' => '{{OBJECTSTORE_S3_BUCKET}}',
          'key' => '{{OBJECTSTORE_S3_KEY}}',
          'secret' => '{{OBJECTSTORE_S3_SECRET}}',
          'region' => '{{OBJECTSTORE_S3_REGION}}',
          'hostname' => '{{OBJECTSTORE_S3_HOST}}',
          'port' => '',
          'objectPrefix' => 'urn:oid:',
          'autocreate' => true,
          'use_ssl' => true,
          'use_path_style' => true,
          'legacy_auth' => false,
        ),
      ),
      'csrf.disabled' => true,
      'trusted_domains' => 
      array (
        0 => '{{NEXTCLOUD_TRUSTED_DOMAINS}}',
      ),
      'datadirectory' => '/var/www/html/data',
      'dbtype' => 'mysql',
      'overwrite.cli.url' => 'https://{{NEXTCLOUD_TRUSTED_DOMAINS}}',
      'dbname' => '{{MYSQL_DATABASE}}',
      'dbhost' => '{{MYSQL_HOST}}:{{MYSQL_PORT}}',
      'dbport' => '',
      'dbtableprefix' => 'oc_',
      'mysql.utf8mb4' => true,
      'dbuser' => '{{MYSQL_USER}}',
      'dbpassword' => '{{MYSQL_PASSWORD}}',
      'drive_email_template_text_left' => '{{DRIVE_EMAIL_TEMPLATE_TEXT_LEFT}}',
      'drive_email_template_plain_text_left' => '{{DRIVE_EMAIL_TEMPLATE_PLAIN_TEXT_LEFT}}',
      'drive_email_template_url_left' => '{{DRIVE_EMAIL_TEMPLATE_URL_LEFT}}',
      'gs.enabled' => '{{GS_ENABLED}}',
      'gs.federation' => '{{GS_FEDERATION}}',
      'gss.discovery.manual.mapping.file' => '/var/www/html/mappingfile.json',
      'gss.discovery.manual.mapping.parameter' => 'urn:oid:1.3.6.1.4.1.5923.1.1.1.6',
      'gss.discovery.manual.mapping.regex' => true,
      'gss.jwt.key' => '{{GSS_JWT_KEY}}',
    );
