apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: proxysql
  namespace: proxysql
  labels:
    app: proxysql
spec:
  replicas: 3
  serviceName: proxysqlcluster
  selector:
    matchLabels:
      app: proxysql
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: proxysql
    spec:
      restartPolicy: Always
      volumes:
        - name: proxysql-data
          persistentVolumeClaim:
            claimName: proxysql-shared-storage-claim
        - name: proxysql-etc
          persistentVolumeClaim:
            claimName: proxysql-etc-storage-claim
      containers:
      - image: proxysql/proxysql:2.3.1
        name: proxysql
        volumeMounts:
        - name: proxysql-data
          mountPath: /var/lib/proxysql
          subPath: data
        volumeMounts:
        - name: proxysql-etc
          mountPath: /etc
          subPath: etc
        ports:
        - containerPort: 6033
          name: proxysql-mysql
        - containerPort: 6032
          name: proxysql-admin
      initContainers:
      - image: proxysql/proxysql:2.3.1
        name: init-config
        volumeMounts:
        - name: proxysql-config-template
          mountPath: /tmp/proxysql.cnf.template
          subPath: proxysql.cnf
        env:
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: proxysql-secret
              key: "proxysql_admin_password"
        - name: CLUSTER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: proxysql-secret
              key: "proxysql_cluster_password"
        - name: MONITOR_PASSWORD
          valueFrom:
            secretKeyRef:
              name: proxysql-secret
              key: "proxysql_monitor_password"
        - name: KANO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: proxysql-secret
              key: "proxysql_kano_password"
        command: ["/bin/sh", "-c", "envsubst < '/tmp/proxysql.cnf.template' > '/etc/proxysql.cnf'"]
      volumes:
      - name: proxysql-config-template
        configMap:
          name: proxysql-configmap
          items:
            - key: "proxysql.cnf"
              path: "proxysql.cnf"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: proxysql-shared-storage-claim
  namespace: proxysql
  annotations:
    volume.beta.kubernetes.io/storage-class: openebs-jiva-3repl
spec:
  storageClassName: openebs-jiva-3repl
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: proxysql-etc-storage-claim
  namespace: proxysql
  annotations:
    volume.beta.kubernetes.io/storage-class: openebs-jiva-3repl
spec:
  storageClassName: openebs-jiva-3repl
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
