apiVersion: v1
kind: ConfigMap
metadata:
  name: proxysql-configmap
data: 
  proxysql.cnf: |
    datadir="/var/lib/proxysql"

    admin_variables=
    {
        admin_credentials="admin:${ADMIN_PASSWORD};cluster:${CLUSTER_PASSWORD}"
        mysql_ifaces="0.0.0.0:6032"
        refresh_interval=2000
        cluster_username="cluster"
        cluster_password="${CLUSTER_PASSWORD}"
    }

    mysql_variables=
    {
        threads=4
        max_connections=2048
        default_query_delay=0
        default_query_timeout=36000000
        have_compress=true
        poll_timeout=2000
        interfaces="0.0.0.0:6033;/tmp/proxysql.sock"
        default_schema="information_schema"
        stacksize=1048576
        server_version="8.0.23"
        connect_timeout_server=3000
        monitor_username="monitor"
        monitor_password="${MONITOR_PASSWORD}"
        monitor_history=600000
        monitor_connect_interval=60000
        monitor_ping_interval=10000
        monitor_read_only_interval=1500
        monitor_read_only_timeout=500
        ping_interval_server_msec=120000
        ping_timeout_server=500
        commands_stats=true
        sessions_sort=true
        connect_retries_on_failure=10
    }

    mysql_galera_hostgroups =
    (
        {

            writer_hostgroup=10
            backup_writer_hostgroup=20
            reader_hostgroup=30
            offline_hostgroup=9999
            max_writers=1
            writer_is_also_reader=2
            max_transactions_behind=30
            active=1
        }
    )
    mysql_query_rules =
    (
        {
            rule_id=100
            active=1
            match_pattern="^SELECT .* FOR UPDATE"
            destination_hostgroup=10
            apply=1
        },
        {
            rule_id=200
            active=1
            match_pattern="^SELECT .*"
            destination_hostgroup=30
            apply=1
        },
        {
            rule_id=300
            active=1
            match_pattern=".*"
            destination_hostgroup=10
            apply=1
        }
    )
    mysql_servers =
    (
        { address="multinode-db1.drive.test.sunet.se" , port=3306 , hostgroup=10, max_connections=100 },
        { address="multinode-db2.drive.test.sunet.se" , port=3306 , hostgroup=20, max_connections=100 },
        { address="multinode-db3.drive.test.sunet.se" , port=3306 , hostgroup=30, max_connections=100 }
    )

    mysql_users =
    (
        { username = "kano", password = "${KANO_PASSWORD}", default_hostgroup = 10, active = 1 }
    )

    proxysql_servers =
    (
        { hostname = "proxysql-0.proxysqlcluster", port = 6032, weight = 1 },
        { hostname = "proxysql-1.proxysqlcluster", port = 6032, weight = 1 },
        { hostname = "proxysql-2.proxysqlcluster", port = 6032, weight = 1 }
    )
