---
apiVersion: v1
kind: Service
metadata:
  name: multinode-db1.drive.test.sunet.se
  namespace: proxysql
spec:
  type: ExternalName
  externalName: multinode-db1.drive.test.sunet.se
  ports:
    - port: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: multinode-db2.drive.test.sunet.se
  namespace: proxysql
spec:
  type: ExternalName
  externalName: multinode-db2.drive.test.sunet.se
  ports:
    - port: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: multinode-db3.drive.test.sunet.se
  namespace: proxysql
spec:
  type: ExternalName
  externalName: multinode-db3.drive.test.sunet.se
  ports:
    - port: 3306
