apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: argocd-server
    name: argocd-server
    namespace: argocd
  spec:
    ports:
    - port: 443
      protocol: TCP
      targetPort: 443
    selector:
      app: argocd-server
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
