namespace: sunetrds

resources:
- describo-ingress.yml 
- doris-deployment.yml  
- doris-service.yaml 
- rds-ingress.yml
- sunet-service.yml
- sunetrds-namespace.yml


helmChartInflationGenerator:
- chartName: all
  chartRepoUrl: https://www.research-data-services.org/charts/stable
  chartVersion: 0.2.2
  releaseName: sciebords
  releaseNamespace: sunetrds 
  # override with these custom values
  values: values.yaml
