verify_ssl: "False"
global:
  image:
    tag: v0.1.9
  namespace:
    create: false
    name: sunetrds
  describo:
    api_secret: IAMSECRET
    domain: describo-sunet.drive.sunet.se
  rds:
    domain: rds-sunet.drive.sunet.se
  domains:
    - name: sunet.drive.sunet.se
      ADDRESS: https://sunet.drive.sunet.se
      OAUTH_CLIENT_ID: some_id
      OAUTH_CLIENT_SECRET: some_secret
      SUPPORT_EMAIL: drive@sunet.se
      MANUAL_URL: usermanual.side.com
layer0-describo:
  postgresql:
    postgresqlDatabase: describo
    postgresqlUsername: admin
    postgresqlPassword: admin
  environment:
    ADMIN_PASSWORD: IAMSECRET
redis:
  startupProbe:
    enabled: false
  readinessProbe:
    enabled: false
  livenessProbe:
    enabled: false
  volumePermissions:
    enabled: true
layer0-web:
  environment:
    SECRET_KEY: 1234
layer1-port-owncloud:
  enabled: true
layer1-port-zenodo:
  enabled: false
  environment:
    ADDRESS: https://sandbox.zenodo.org
    OAUTH_CLIENT_ID: ABC
    OAUTH_CLIENT_SECRET: XYZ
proxy:
  http_proxy: ""
  https_proxy: ""
  no_proxy: "*"
