---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kano-node
  namespace: kano
  labels:
    app: kano-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kano-node
  template:
    metadata:
      creationTimestamp:
      labels:
        app: kano-node
    spec:
      containers:
      - name: nextcloud 
        image: nextcloud 
        resources: {}
        env:
          - name: NEXTCLOUD_ADMIN_USER
            value: admin
          - name: NEXTCLOUD_TRUSTED_DOMAINS
            value: kano.drive.test.sunet.se
          - name: MYSQL_DATABASE
            value: nextcloud_kano
          - name: MYSQL_USER
            value: kano
          - name: MYSQL_HOST
            value: multinode_db
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: db_password
          - name: REDIS_HOST
            value: redis
          - name: OBJECTSTORE_S3_HOST
            value: s3.sto4.safedc.net
          - name: OBJECTSTORE_S3_BUCKET
            value: primary-kano-drive-test.sunet.se
          - name: OBJECTSTORE_S3_KEY
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: s3_key
          - name: OBJECTSTORE_S3_SECRET
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: s3_secret
          - name: OBJECTSTORE_S3_USEPATH_STYLE
            value: true
          - name: OBJECTSTORE_S3_AUTOCREATE
            value: true
      - name: redis
        image: redis:alpine 
        resources: {}
  strategy: {}
status: {}
