---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kano-node
  namespace: kano
  labels:
    app: kano-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kano-node
  template:
    metadata:
      creationTimestamp:
      labels:
        app: kano-node
    spec:
      volumes:
        - name: server-storage
          persistentVolumeClaim:
            claimName: nextcloud-shared-storage-claim
      containers:
      - name: nextcloud 
        image: nextcloud 
        volumeMounts:
          - name: server-storage
            mountPath: /var/www/html
            subPath: server-data
        env:
          - name: MYSQL_DATABASE
            value: "kano_nextcloud"
          - name: MYSQL_USER
            value: "kano"
          - name: MYSQL_HOST
            value: "proxysql.proxysql"
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: "db_password"
          - name: MYSQL_PORT
            value: "6033"
          - name: NEXTCLOUD_TRUSTED_DOMAINS
            value: "kano.drive.test.sunet.se"
          - name: NEXTCLOUD_ADMIN_USER
            value: _kano
          - name: NEXTCLOUD_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nc-secret
                key: "nc_admin_password"
          - name: OBJECTSTORE_S3_REGION
            value: "us-east-1"
          - name: OBJECTSTORE_S3_HOST
            value: "s3.sto4.safedc.net"
          - name: OBJECTSTORE_S3_BUCKET
            value: "primary-kano-drive-test.sunet.se"
          - name: OBJECTSTORE_S3_KEY
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: "s3_key"
          - name: OBJECTSTORE_S3_SECRET
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: "s3_secret"
          - name: OBJECTSTORE_S3_USEPATH_STYLE
            value: "true"
          - name: OBJECTSTORE_S3_AUTOCREATE
            value: "true"
          - name: OBJECTSTORE_S3_SSL
            value: "true"
          - name: REDIS_HOST
            value: "redis.redis"
        resources: {}
  strategy: {}
status: {}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud-shared-storage-claim
  namespace: kano
  annotations:
    volume.beta.kubernetes.io/storage-class: openebs-jiva-3repl
spec:
  storageClassName: openebs-jiva-3repl
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
