apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: redis
  name: redis
  namespace: redis
spec:
  ports:
  - name: redis-port
    nodePort: 30379
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
    role: master
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: rediscluster
  namespace: redis
  labels:
    app: redis
spec:
  clusterIP: None
  ports:
  - port: 6379
    name: redis-port
  selector:
    app: redis
