apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: redis
  name: redis
  namespace: redis
spec:
  ports:
  - name: redis
    nodePort: 30379
    port: 6379
    targetPort: redis
  selector:
    app: redis
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: rediscluster
  namespace: redis
  labels:
    app: redis
spec:
  clusterIP: None
  ports:
  - port: 6379
    name: redis
  selector:
    app: redis
